export const ADD_STAFF = 'ADD_STAFF';
export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';

export const ADD_STAFFS = 'ADD_STAFFS';

export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const DEPARTMENT_LOADING = 'DEPARTMENT_LOADING';
export const DEPARTMENT_FAILED = 'DEPARTMENT_FAILED';

export const ADD_PAYROLL = 'ADD_PAYROLL';
export const PAYROLL_LOADING = 'PAYROLL_LOADING';
export const PAYROLL_FAILED = 'PAYROLL_FAILED';

export const ADD_STAFF_DEPART = 'ADD_STAFF_DEPART';
export const STAFFS_DEPART_LOADING = 'STAFFS_DEPART_LOADING';
export const STAFFS_DEPART_FAILED = 'STAFFS_DEPART_FAILED';